iso: Use same go version (1.25.5)
We still use go 1.23.4 which fail to buid runc when updating nerdctl to
latest stable version[1]:

    go build -trimpath "-buildmode=pie"  -tags "seccomp" -ldflags "-X main.gitCommit=8bd78a9977e604c4d5f67a7415d7b8b8c109cdc4  " -o runc .
    # github.com/opencontainers/runc/libcontainer/configs
    libcontainer/configs/config.go:332:25: undefined: strings.SplitSeq

strings.SplitSeq was added in go 1.24.0[2]

We use the same GO_VERSION variable for the iso build. This overrides
GO_VERSION in the buildroot go package.

Testing shows that go is installed from binary release, so we have now
checksums for both source and binary releases for amd64 and arm64.
Buildroot builtin go.hash does the same[3].

[1] https://storage.cloud.google.com/minikube-builds/logs/22099/0a27ed4/iso_build.txt
[2] https://pkg.go.dev/strings#SplitSeq
[3] https://github.com/buildroot/buildroot/blob/master/package/go/go.hash